spring:
  application:
    name: ShahbazTrades

  jackson:
    deserialization:
      fail-on-null-for-primitives: false
      accept-empty-string-as-null-object: true

  main:
    lazy-initialization: true

  threads:
    virtual:
      enabled: false

  jmx:
    enabled: false

  mongodb:
    uri: ${MONGO_URI}

  services:
    session-manager:
      url: ${SESSION_MANAGER_URI}

server:
  address: 0.0.0.0
  port: ${PORT:8080}
  jetty:
    threads:
      min: 32
      max: 200
      idle-timeout: 60000
