spring:
  application:
    name: ShahbazTrades

  jackson:
    deserialization:
      fail-on-null-for-primitives: false
      accept-empty-string-as-null-object: true

  main:
    lazy-initialization: true

  threads:
    virtual:
      enabled: true

  jmx:
    enabled: false

  mongodb:
    uri: ${MONGO_URI}

  services:
    session-manager:
      url: ${SESSION_MANAGER_URI}

server:
  port: ${PORT:8080}
  jetty:
    threads:
      min: 8
      max: 20
